FROM ubuntu:latest

RUN apt-get update -y && \
    apt-get install -y mysql-server && \
    rm -rf /var/lib/apt/lists/*

RUN sed -i "s/^bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mysql.conf.d/mysqld.cnf

COPY script.sh /usr/local/bin/script.sh
RUN chmod +x /usr/local/bin/script.sh

EXPOSE 3306
#sdsas

CMD [ "/usr/local/bin/script.sh" ]

